pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'joaoasrosa/pandoc:2.5.$(build.buildId)'

steps:
- task: Docker@0
  displayName: 'Build image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    imageName: '$(imageName)'
    includeLatestTag: true

- script: mkdir ./node_modules && npm install --prefix ./ snyk && ./node_modules/.bin/snyk auth $(snyk-token) && ./node_modules/.bin/snyk monitor $(imageName) --docker --org=joaoasrosa
  displayName: 'Monitor vulnerabilities in the Docker image'

- task: Docker@0
  displayName: 'Push image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    action: 'Push an image'
    imageName: '$(imageName)'
    includeLatestTag: true
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))