pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'joaoasrosa/pandoc:1.0.$(build.buildId)'

steps:
- task: Docker@0
  displayName: 'Build image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    imageName: '$(imageName)'
    includeLatestTag: true

- task: jessehouwing.vsts-snyk.vsts-snyk.SnykTask@1
  displayName: 'Scan for vulnerable in the Docker image'
  inputs:
    optServiceEndpoint: Snyk
    optionOrg: joaoasrosa
    optAdditionalArguments: '$(imageName) --docker'
    optionUpgrade: true

- task: Docker@0
  displayName: 'Push image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    action: 'Push an image'
    imageName: '$(imageName)'
    includeLatestTag: true