pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'joaoasrosa/pandoc:1.0.$(build.buildId)'

steps:
- task: Docker@0
  displayName: 'Build image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    imageName: '$(imageName)'
    includeLatestTag: true

- script: npm install snyk && ls && ls ./node_modules/.bin && ./node_modules/.bin/snyk auth $(snyk-token) && ./node_modules/.bin/snyk test $(imageName) --docker --org=joaoasrosa
  displayName: 'Scan for vulnerable in the Docker image'

- task: Docker@0
  displayName: 'Push image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub'
    action: 'Push an image'
    imageName: '$(imageName)'
    includeLatestTag: true